### ISSUE TITLE
Event Handlers Are Not Performant

### ISSUE THREAD

**Issue by beardedtim** [kofile/react-a11y-table#19]
In an application with ~100 rows, the event handlers for drag/mouse move are sucking the performance from the application. This causes choppy, non-performant movement for the consumer of this package.

**Comment by blobor** [comment]
I believe we should add some benchmark tests, so we could compare and monitor our PRs. Thoughts?

**Comment by beardedtim** [comment]
@blobor I really like that idea! Any pointers towards the `benchmark tests` you were imagining? I am going to be working on this issue soon and would like to get comfortable with the tools first.

**Comment by blobor** [comment]
I know there are good library for benchmarking [benchmark.js](https://github.com/bestiejs/benchmark.js)

Regarding React components benchmarking, there are great article which describes one of approaches https://engineering.musefind.com/how-to-benchmark-react-components-the-quick-and-dirty-guide-f595baf1014c

**Comment by beardedtim** [comment]
Awesome! I'll take a look once in office. Thanks for the info!

**Comment by beardedtim** [comment]
Closing due to age
